### PR TITLE
Plugin command refactor and Matrix CS API factoring

### PR DESCRIPTION
**Pull request by kegsay**
Refactoring
- Made a more concrete and "nice" Plugin architecture. Redid all the plugins using this.
- Split out Matrix CS API calls from everything else (will be forked to matrix-org)

Features:
- Multi-commit messages
- Show PR comments
- Add logging options
- Add log rotation
- Add time plugin

### CODE REVIEW

**Comment by Kegsay** [comment]
this is a test

**Comment by kegsay** [comment]
this is a test `with markdown`

**Comment by kegsay** [comment]
flibble

**Comment by kegsay** [comment]
wibble

**Comment by kegsay** [comment]
tibble

**Comment by kegsay** [comment]
another test

**Comment by kegsay** [comment]
one more _test_ _fo this_ `thingy`

**Comment by kegsay** [comment]
I lied, `one more maybe`

**Comment by kegsay** [comment]
or is it?!

**Comment by kegsay** [comment]
will this refresh?

**Comment by kegsay** [comment]
yay! :D

**Comment by kegsay** [comment]
hello `world` how are you? Some lines:
- One
- Two
- Three

I _really_ hope this works.

**Comment by kegsay** [comment]
this is a final test. `of things` **and stuff**

**Pull request merged**
